/*
 * printer_data_types.h
 *
 *  Created on: Feb 25, 2016
 *      Author: johan
 */

#ifndef PRINTER_DATA_TYPES_H_
#define PRINTER_DATA_TYPES_H_

#include <stdint.h>

enum class printer_message : uint8_t{
	REPORT_STARTUP_STATUS = 1,
	REPORT_FIRMWARE_CAPABILITIES_STRING,
	REPORT_OK,
	REPORT_PRINTER_KILLED,
	REPORT_PRINTER_STOPPED,
	REPORT_STEP_RATE_TOO_HIGH,
	REPORT_COLD_EXTRUSION_PREVENTED,
	REPORT_TOO_LONG_EXTRUSION_PREVENTED,
	REPORT_CURRENT_PRINTER_SETTINGS,
	REPORT_SETTINGS_STORED,
	REPORT_SETTINGS_RETRIEVED,
	REPORT_FACTORY_SETTINGS_RESTORED,
	REPORT_ENQUEING_COMMAND,
	REPORT_FIRMWARE_INFORMATION,
	REPORT_FILE_SAVED,
	REPORT_ACTIVE_EXTRUDER,
	REPORT_UNKNOWN_COMMAND,
	REPORT_INVALID_EXTRUDER_SPECIFIED,
	REPORT_WRONG_EXTRUDER_SPECIFIED,
	ISSUE_RESEND_REQUEST,
	REPORT_ERROR_IN_LINE_NUMBER,
	REPORT_ERROR_IN_CHECKSUM,
	REPORT_MISSING_CHECKSUM,
	REPORT_NO_LINE_NUMBER_WITH_CHECKSUM,
	REPORT_TIME_ELAPSED,
	REPORT_FILE_PRINTED,
	REPORT_ENDSTOP_NOT_PRESSED_AFTER_HOMING,
	REPORT_ERROR_ENDSTOP_STILL_PRESSED,
	REPORT_TEMPERATURE_AND_POWER,
	REPORT_WAIT_FOR_TEMPERATURE,
	REPORT_WAIT_FOR_TEMPERATURE_BED,
	REPORT_LCD_BUTTON_INFO,
	REPORT_BED_LEVELING_PROBE_SEQUENCE,
	REPORT_BED_LEVELING_PROBE_POINT,
	REPORT_SINGLE_CAP_PROBE_VALUE,
	REPORT_MICROSTEP_SETTINGS,
	REPORT_ENDSTOP_STATUS,
	REPORT_ENDSTOP_HIT,
	REPORT_CURRENT_POSITION,
	REPORT_PID_EXTRUDER_PARAMETERS,
	REPORT_PID_BED_PARAMETERS,
	SD_CARD_DATA,
	REPORT_FISET_FULL_DATA,
	LAST_COMMAND
};

enum class sdcard_messages : uint8_t{
	BEGIN_FILE_LIST,
	END_FILE_LIST,
	SET_LISTING_SUB_DIR,
	LIST_FILE,
	LAST_SD_MESSAGE
};


#endif /* PRINTER_DATA_TYPES_H_ */
